[project]
name = "sample-kong-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "httpx[http2]>=0.28.1",
    "pytest>=8.4.2",
]
