---
apiVersion: v1
kind: Service
metadata:
  name: grpcbin
  # nginx-ingress では無視される
  # annotations:
  #   # projectcontour.io/upstream-protocol.h2: "443"
  #   projectcontour.io/upstream-protocol.h2c: "80"  # contour で使える
spec:
  # type: ClusterIP
  selector: { app: grpcbin }
  ports: [{ port: 80, targetPort: 9000 }]

---
apiVersion: v1
kind: Pod
metadata: 
  namespace: default
  name: grpcbin
  labels:
    app: grpcbin
spec:
  containers:
  - name: server
    image: moul/grpcbin
    # args: ["/grpcbin", "-grpc-port", "8080", "-insecure"]
    ports: [{containerPort: 9000}]  # 9001(secure)
