---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-mock-schema
  namespace: default
data:
  schema.faker: |
    # GraphQL Faker SDL（最低限の例）
    type User {
      id: ID!
      name: String @fake(type: firstName)
      email: String @fake(type: email)
      age: Int @fake(type: number, options: {min: 18, max: 65})
    }

    type Query {
      users: [User]! @listLength(min: 3, max: 8)
    }

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: graphql-mock
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - image: apisguru/graphql-faker:latest
          args: ["--open=false", "--port", "8080", "/schema/schema.faker"]
          startupProbe:
            tcpSocket: { port: 8080 }
            periodSeconds: 2
            failureThreshold: 60
          readinessProbe:
            tcpSocket: { port: 8080 }
            periodSeconds: 2
            failureThreshold: 3
          livenessProbe:
            tcpSocket: { port: 8080 }
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: schema
              mountPath: /schema
      volumes:
        - name: schema
          configMap:
            name: graphql-mock-schema
