volumes:
  platform-k0s:
    name: platform-k0s


networks:
  # ip が変わると kubernetes が動かなくなるので 固定ipで管理
  fixed_compose_network:
    name: fixed_compose_network
    external: true

services:
  kube:
    # image: docker.io/k0sproject/k0s:v1.32.8-k0s.0
    build:
      context: ./containers/k0s
    container_name: kube-master
    hostname: kube-master
    environment:
      APP_DOMAIN: {{ (ds "cfg").merged.kube.knative_alias | quote }}  # Windows から アクセスできない（デフォルトでローカルホストでしか転送が効かない）
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      fixed_compose_network:
        ipv4_address: {{ (ds "cfg").merged.kube.knative_address | quote }}
        aliases:
          - {{ (ds "cfg").merged.kube.knative_alias | quote }}
    privileged: true
    ports:
      - "30080:30080"  # for ingress
      - "30443:30443"  # for ingress
      - "6443:6443"
    restart: unless-stopped
    # taint: controller 専用とし、pod はデプロイできない
    command: ["k0s","controller","--enable-worker","--no-taints", "--single"]
    tmpfs:
      - /run
    volumes:
      - platform-k0s:/var/lib/k0s
      - /dev/kmsg:/dev/kmsg:ro  # カーネルログ
      # - /var/log/pods
      - ./configs/kube:/mnt/kube
      - ./volumes/step/certs:/certs:ro
    