apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
  name: hello-ksvc-grpc
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: moul/grpcbin
          ports:
            - name: h2c
              containerPort: 9000
