apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
  name: hello-ksvc-http
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          env:
            - name: TARGET
              value: "Edge!!"
